// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		AppFooter: typeof import('C:/REEVE/projects/vitailse/src/components/AppFooter.vue')['default'];
		AppHeader: typeof import('C:/REEVE/projects/vitailse/src/components/AppHeader.vue')['default'];
		AppSidebar: typeof import('C:/REEVE/projects/vitailse/src/components/AppSidebar.vue')['default'];
		'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default'];
		'IconCi:hamburger': typeof import('~icons/ci/hamburger')['default'];
		'IconIconParkOutline:hamburgerButton': typeof import('~icons/icon-park-outline/hamburger-button')['default'];
	}
}

export {};
