import { createApp } from 'vue';
import App from '@/App.vue';
import '@/styles/index.css';
import { createHead } from '@vueuse/head';
import router from '@/router';
const app = createApp(App);
const head = createHead();
app.use(router);
app.use(head);
app.mount('#app');
